updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.12." }
]

buildRoots = [
  "."
  "test-project-docker"
  "test-project-simple"
  "test-project-windows"
  "test-project-jdkpackager"
  "integration-tests-ansible/test-project-play-rpm"
]
