#! /bin/bash

### BEGIN INIT INFO
# Provides:	${{app_name}}
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: ${{descr}}
### END INIT INFO

test -e /etc/default/${{app_name}} && source /etc/default/${{app_name}}
source /lib/init/vars.sh
source /lib/lsb/init-functions

get_java_cmd() {
  if [ -x "$JAVA_HOME/bin/java" ]; then
    echo "$JAVA_HOME/bin/java"
  else
    echo $(which java)
  fi
}

PIDFILE=/var/run/${{app_name}}.pid

if [ -z "$DAEMON_USER" ]; then
    DAEMON_USER=${{daemon_user}}
fi

if [ -z "$JAVA_CMD" ]; then
    JAVA_CMD=$(get_java_cmd)
fi

# smb could define some additional options in $RUN_OPTS
RUN_CMD="-cp ${{app_classpath}} ${{app_main_class}} $RUN_OPTS"


start_daemon() {
    log_daemon_msg "Starting" "${{app_name}}"
    start-stop-daemon --background --chuid "$DAEMON_USER" --make-pidfile --pidfile "$PIDFILE" --exec "$JAVA_CMD" --start -- $RUN_CMD
    log_end_msg $?
}


stop_daemon() {

  log_daemon_msg "Stopping" "${{app_name}}"
	  if start-stop-daemon --status --pidfile "$PIDFILE"; then
		  start-stop-daemon --stop --pidfile "$PIDFILE"
		  log_end_msg $?
	  else
		  log_progress_msg "not running"
		  log_end_msg 1
	  fi

    RETVAL=$?
    [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
}

case "$1" in

  start)
    start_daemon
    exit $?
	  ;;
  stop)
    stop_daemon
    exit $?
	  ;;
  restart)
    stop_daemon
    start_daemon
    exit $?
    ;;
  status)
    start-stop-daemon --status --pidfile "$PIDFILE"
    case "$?" in
    0)
      echo "${{app_name}} is running"
      ;;
    1)
      echo "${{app_name}} is not running and the pid file exists"
      ;;
    3)
      echo "${{app_name}} is not running"
      ;;
    *)
      echo "Unable to determine ${{app_name}} status"
      ;;
  esac
  exit $?
    ;;
  *)
    log_daemon_msg "Usage: /etc/init.d/${{app_name}} {start|stop|restart|status}"
    ;;
esac
exit 0