#! /bin/sh

### BEGIN INIT INFO
# Provides:	${{app_name}}
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description: ${{descr}}
### END INIT INFO

test -e /etc/default/${{app_name}} && source /etc/default/${{app_name}}
source /lib/init/vars.sh
source /lib/lsb/init-functions

get_java_cmd() {
  if [ -x "$JAVA_HOME/bin/java" ]; then
    echo "$JAVA_HOME/bin/java"
  else
    echo `which java`
  fi
}

PIDFILE=/var/run/${{app_name}}.pid

if [ -z "$DAEMON_USER" ]; then
    DAEMON_USER=${{daemon_user}}
fi

if [ -z "$JAVA_CMD" ]; then
    JAVA_CMD=$(get_java_cmd)
fi

# smb could define some additional options in $RUN_OPTS
RUN_CMD="-cp ${{app_classpath}} ${{app_main_class}} $RUN_OPTS"


start_daemon() {
    log_daemon_msg "Starting ${{app_name}}"
    start-stop-daemon --background --start --chuid "$DAEMON_USER" --make-pidfile --pidfile "$PIDFILE" --exec "$JAVA_CMD" --start -- $RUN_CMD
}


stop_daemon() {
    log_daemon_msg "Stopping ${{app_name}}"
	start-stop-daemon --stop --pidfile "$PIDFILE" --user "$DAEMON_USER"

    RETVAL=$?
    [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
    exit 2
}


case "$1" in

start)
    start_daemon
	;;
stop)
    stop_daemon
	;;
restart)
    stop_daemon
    start_daemon
    ;;
*)
    log_daemon_msg "Usage: /etc/init.d/${{app_name}} {start|stop}"
    exit 2
    ;;
esac
exit 0