#! /bin/sh

### BEGIN INIT INFO
# Provides:	${{app_name}}
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description: ${{descr}}
### END INIT INFO

PIDFILE=/var/run/${{app_name}}.pid

. /lib/init/vars.sh
. /lib/lsb/init-functions

#TODO: fix this
get_java_cmd() {
  if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo "$JAVA_HOME/bin/java"
  else
    echo "java"
  fi
}

JAVA_CMD=$(get_java_cmd)

RUN_CMD=$JAVA_CMD -cp ${{app_classpath}} ${{app_main_class}}

case "$1" in

start)  log_daemon_msg "Starting ${{app_name}}"

        start-stop-daemon --background --start --make-pidfile --pidfile $PIDFILE --exec $RUN_CMD

	;;
stop)   log_daemon_msg "Stopping ${{app_name}}"

	start-stop-daemon --stop --pidfile $PIDFILE --chuid $DAEMONUSER

        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        exit 2
	;;
*)      log_daemon_msg "Usage: /etc/init.d/${{app_name}} {start|stop}"
        exit 2
        ;;
esac
exit 0